"""MD Fisher vs MJ Fisher — two different men, both announced "Matthew Fisher".

MD Fisher (cricinfo 639080, cricsheet 8f2dfebf) is the England/Yorkshire seamer: London Spirit in
The Hundred Men's 2026 and the ENG v PAK Test squad. MJ Fisher (cricinfo 1129635, cricsheet
7068c81e) is a New Zealander in the NZ v WI ODI squad. Three squads announced the bare, ambiguous
"Matthew Fisher", which alias-resolved to MJ — so when the official cricsheet card named MD, the
settlement store's write-once guard (match_key, pid) saw a pid it had never settled and minted a
SECOND row for an already-settled match: 06 Aug, MTLSP v MTMILO, 38 points under both pids.

The fix is the announced name, not a fuzzy tiebreak: each squad now names the man it means, each
full name is bridged to its id, and the bare spelling resolves to NOTHING so it raises a question
instead of silently picking one of two real people.
"""
import json
import os

import build_registry as br

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(br.__file__))) if False else \
    os.path.dirname(os.path.abspath(br.__file__))


def _name2ci():
    br.NAME2CI = {}
    br.load_crosswalk()
    br.load_ci_bridges()
    return br.NAME2CI


def test_each_full_name_anchors_to_its_own_man():
    n = _name2ci()
    assert n.get("matthew david fisher") == "639080"
    assert n.get("matthew john fisher") == "1129635"
    assert n.get("md fisher") == "639080"


def test_the_ambiguous_bare_spelling_resolves_to_nobody():
    # Not a defect — the point. A name that two real people share may only raise a question.
    # Resolving it either way is how 38 points landed on the wrong identity in the first place.
    assert _name2ci().get("matthew fisher") is None


def test_the_two_ids_are_two_different_cricsheet_people():
    _name2ci()
    assert br.CI2CS.get("639080") == "8f2dfebf"
    assert br.CI2CS.get("1129635") == "7068c81e"


# auction_squads.json is REGENERATED by tour-sync.yml from cricket-auction-helper's TS squad
# files, so editing it here would be overwritten. It is fixed at its source (commit b8b5c80 in
# that repo) — which matters, because it is the seed tour_sync reads for a newly ingested tour.
GENERATED = {"auction_squads.json"}


def test_no_hand_maintained_squad_announces_the_ambiguous_spelling_any_more():
    offenders = []
    for f in sorted(os.listdir(ROOT)):
        if not f.endswith("squads.json") or f in GENERATED:
            continue
        if '"Matthew Fisher"' in open(os.path.join(ROOT, f)).read():
            offenders.append(f)
    assert not offenders, f"these squads still announce the ambiguous name: {offenders}"


def test_the_squads_name_the_man_they_mean():
    def names(f):
        return open(os.path.join(ROOT, f)).read()
    assert '"Matthew David Fisher"' in names("the_hundred_men_s_competition_2026_squads.json")
    assert '"Matthew David Fisher"' in names("eng_pak_test_2026_squads.json")
    assert '"Matthew John Fisher"' in names("nz_wi_men_odi_squads.json")
